src/mod/applications/mod_cv/mod_cv.cpp: fix build with opencv 3.4.9
Use cvScalar instead of CV_RGB to avoid the following build failure with
opencv 3.4.9:

mod_cv.cpp:693:24: error: conversion from ‘cv::Scalar {aka cv::Scalar_<double>}’ to non-scalar type ‘CvScalar’ requested
         CvScalar col = CV_RGB((float)255 * object_neighbors / max_neighbors, 0, 0);
                        ^

Indeed, CV_RGB is defined as cv::Scalar instead of cvScalar since
version 3.4.2 and
https://github.com/opencv/opencv/commit/7f9253ea0a9fe2635926379420002dbf0c3fce0f

It should be noted that CV_RGB(r,g,b) = cvScalar(b,g,r,0)

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>