[core] Fix copy/paste mistake in switch_xml.h
Commit 7907994 introduced a copy/paste mistake that may result in
compile failure:

In file included from ../../../../src/include/switch.h:134,
                 from mod_xml_ldap.c:34:
mod_xml_ldap.c: In function 'xml_ldap_search':
../../../../src/include/switch_xml.h:236:68: error: implicit declaration of function 'switch_xml_toxml_buf'; did you mean 'switch_xml_toxml_buf_ex'? [-Werror=implicit-function-declaration]
 #define switch_xml_toxml_buf(xml, buf, buflen, offset, prn_header) switch_xml_toxml_buf(xml, buf, buflen, offset, prn_header, USE_UTF_8_ENCODING);
                                                                    ^~~~~~~~~~~~~~~~~~~~
mod_xml_ldap.c:764:9: note: in expansion of macro 'switch_xml_toxml_buf'
         switch_xml_toxml_buf(xml, buf, 0, 0, 1);
         ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [Makefile:710: mod_xml_ldap_la-mod_xml_ldap.lo] Error 1

This commit fixes the mistake.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>