FS-9840 mod_sofia: fix redefine warning
This fixes the following compile-time warning:

make[8]: Entering directory '/home/sk/tmp/lede/build_dir/target-mips_24kc_musl-1.1.15/freeswitch-1.8.0/src/mod/endpoints/mod_sofia'
  CC       mod_sofia_la-mod_sofia.lo
  CC       mod_sofia_la-sofia.lo
  CC       mod_sofia_la-sofia_glue.lo
  CC       mod_sofia_la-sofia_presence.lo
  CC       mod_sofia_la-sofia_reg.lo
  CC       mod_sofia_la-sofia_media.lo
  CC       mod_sofia_la-sip-dig.lo
In file included from sip-dig.c:137:0:
/home/sk/tmp/lede/build_dir/target-mips_24kc_musl-1.1.15/freeswitch-1.8.0/libs/sofia-sip/libsofia-sip-ua/bnf/../../config.h:522:0: error: "__BYTE_ORDER" redefined [-Werror]
 #define __BYTE_ORDER __BIG_ENDIAN
 ^
In file included from /home/sk/tmp/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/sys/types.h:70:0,
                 from ../../../../src/include/switch.h:107,
                 from sip-dig.c:135:
/home/sk/tmp/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/endian.h:11:0: note: this is the location of the previous definition
 #define __BYTE_ORDER __BYTE_ORDER__
 ^
cc1: all warnings being treated as errors

SWITCH_BYTE_ORDER is already used elsewhere in FS source and takes care
of changing byte order without causing a warning

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>